---
---
Has recibido una nueva solicitud de las partes interesadas de Zoop, en la que será necesario agregar más columnas de otra base de datos a la tabla consolidada en el video anterior.

A diferencia de las actividades que estamos realizando en los videos de este curso, aquí también utilizaremos esta nueva base para la construcción de los visuales dentro de los ejercicios de "Manos a la obra", enfocándonos en las demandas presentadas en las instrucciones de los ejercicios.

Los archivos que vamos a utilizar en esta parte del proyecto son:

Datos de clientes del e-commerce de Zoop, separados por el código identificador de la compra.
Datos de ventas del e-commerce de Zoop en 2023, separados por el código identificador de la compra.
Datos de clientes pre-registrados en Zoop Pay, la billetera digital de Zoop que está en proceso de implementación.
Estos datos se leerán a través de enlaces (URL) que compartimos a continuación:

---
---

In [1]:
url_clientes = "https://gist.githubusercontent.com/ahcamachod/d08898e1cc84c7271856e78d9558ca3d/raw/2f7e1fa53711efe6433a5c5ec79948f600591cb9/clientes_zoop.csv"
url_ventas = "https://gist.githubusercontent.com/ahcamachod/966d7162a3c3a2769b8770b35abf1bcc/raw/d79941b3fa46a450f3611589abd8663399c1277b/ventas_zoop.csv"
url_zoop_pay = "https://gist.githubusercontent.com/ahcamachod/ce728231a836a973c0df94a9f03ed871/raw/8db6da43d7cd94fcab937208067d0fceb521b78c/zoop_pay.csv"

In [3]:
clientes = pd.read_csv(url_clientes)
ventas = pd.read_csv(url_ventas)
zoop_pay = pd.read_csv(url_zoop_pay)

In [4]:
clientes

,ID_compra,ID_cliente,ciudad,estado,region,edad,sexo_biologico,cashback,nota
0,904,8972,Oaxaca de Juárez,Oaxaca,Sur,49,Masculino,No,9
1,4613,5120,Ciudad de México,Ciudad de México,Centro,49,Femenino,No,9
2,5579,1847,Ciudad de México,Ciudad de México,Centro,24,Femenino,No,8
3,2405,2846,Ciudad de México,Ciudad de México,Centro,38,Femenino,Sí,7
4,2485,2715,Chihuahua,Chihuahua,Noroeste,30,Femenino,No,10
...,...,...,...,...,...,...,...,...,...
6164,700,3769,Chalco,Estado de México,Centro,29,Femenino,Sí,10
6165,1772,4557,Monterrey,Nuevo León,Noreste,31,Masculino,No,9
6166,6011,8531,Oaxaca de Juárez,Oaxaca,Sur,48,Femenino,No,9
6167,4684,9875,Chalco,Estado de México,Centro,37,Femenino,Sí,9
6168,732,3983,Chalco,Estado de México,Centro,55,Masculino,No,8

In [5]:
ventas

,ID_compra,fecha,horario,categoria,precio_unitario,cantidad,envio,metodo_pago
0,6,2023-01-03,20:40,Electrónicos,4457.9,4,713.26,Paypal
1,5,2023-01-03,21:48,Herramientas y construcción,115.9,1,0.00,Transferencia
2,9,2023-01-03,17:08,Belleza e higiene,68.9,2,13.78,Tarjeta de Crédito
3,4,2023-01-03,14:29,Herramientas y construcción,80.9,5,40.45,Transferencia
4,8,2023-01-03,18:02,Belleza e higiene,165.0,4,0.00,Transferencia
...,...,...,...,...,...,...,...,...
6164,6141,2023-12-31,17:49,Electrodomésticos,1509.9,5,377.48,Tarjeta de Crédito
6165,6148,2023-12-31,23:02,Papelería y oficina,14.0,2,3.36,Transferencia
6166,6123,2023-12-31,21:25,Alimentos y bebidas,77.9,1,7.79,Tarjeta de Crédito
6167,6147,2023-12-31,21:38,Libros,142.9,4,17.15,Tarjeta de Crédito
6168,6122,2023-12-31,22:11,Belleza e higiene,89.9,5,13.48,Tarjeta de Crédito

In [6]:
zoop_pay

      ID_cliente zoop_pay
0           6149       No
1           9491       Sí
2           5288       No
3           9679       Sí
4           1380       No
...          ...      ...
4448        5291       No
4449        6035       No
4450        7361       No
4451        4516       No
4452        8022       Sí

[4453 rows x 2 columns]

In [12]:
df = pd.merge(ventas, clientes, on='ID_compra', how='inner')

In [14]:
df = df[["ID_compra", "fecha", "horario", "categoria", "precio_unitario", "cantidad", "envio", "metodo_pago", "ID_cliente", "edad", "sexo_biologico", "ciudad", "estado", "region", "cashback", "nota"]]

In [15]:
df

,ID_compra,fecha,horario,categoria,precio_unitario,cantidad,envio,metodo_pago,ID_cliente,edad,sexo_biologico,ciudad,estado,region,cashback,nota
0,6,2023-01-03,20:40,Electrónicos,4457.9,4,713.26,Paypal,6149,30,Masculino,Hermosillo,Sonora,Noroeste,Sí,10
1,5,2023-01-03,21:48,Herramientas y construcción,115.9,1,0.00,Transferencia,9491,36,Masculino,Ciudad de México,Ciudad de México,Centro,Sí,8
2,9,2023-01-03,17:08,Belleza e higiene,68.9,2,13.78,Tarjeta de Crédito,5288,39,Femenino,Aguascalientes,Aguascalientes,Centro-Norte,No,7
3,4,2023-01-03,14:29,Herramientas y construcción,80.9,5,40.45,Transferencia,9679,35,Masculino,Veracruz,Veracruz,Golfo,Sí,9
4,8,2023-01-03,18:02,Belleza e higiene,165.0,4,0.00,Transferencia,1380,50,Masculino,Ciudad de México,Ciudad de México,Centro,No,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6164,6141,2023-12-31,17:49,Electrodomésticos,1509.9,5,377.48,Tarjeta de Crédito,6035,49,Masculino,Cholula,Puebla,Centro-Sur,No,10
6165,6148,2023-12-31,23:02,Papelería y oficina,14.0,2,3.36,Transferencia,7361,40,Masculino,Mazatlán,Sinaloa,Noroeste,Sí,7
6166,6123,2023-12-31,21:25,Alimentos y bebidas,77.9,1,7.79,Tarjeta de Crédito,4516,32,Masculino,Aguascalientes,Aguascalientes,Centro-Norte,No,8
6167,6147,2023-12-31,21:38,Libros,142.9,4,17.15,Tarjeta de Crédito,3786,34,Masculino,Guadalajara,Jalisco,Occidente,No,9
6168,6122,2023-12-31,22:11,Belleza e higiene,89.9,5,13.48,Tarjeta de Crédito,8022,20,Femenino,Tlaquepaque,Jalisco,Occidente,Sí,9

In [ ]:
import pandas as pd

# Ejemplo de cómo cargar los DataFrames, si es necesario:
# ventas = pd.read_csv('ruta_al_archivo_de_ventas.csv')
# clientes = pd.read_csv('ruta_al_archivo_de_clientes.csv')

# Uniendo las bases "ventas" y "clientes" usando la columna "ID_compra" como clave
df = pd.merge(ventas, clientes, on="ID_compra")

# Organizando las columnas en la secuencia especificada
columnas_ordenadas = ["ID_compra", "fecha", "hora", "categoría", "precio_unitario", "cantidad", "envio", "metodo_pago", "ID_cliente", "edad", "sexo_biologico", "ciudad", "estado", "region", "cashback", "nota"]

df = df[columnas_ordenadas]

# Mostrando las primeras filas del DataFrame resultante para verificación
df.head()

---
---
Nota que en este código generado por ChatGPT necesitamos ajustar la parte que lee los datos de las bases, pasando los enlaces como creados al inicio del cuaderno de Desafíos.

Ahora, vamos a la segunda parte del problema, concatenando este DataFrame creado con la base Zoop Pay y ajustando la columna de fecha a formato datetime. Por lo tanto, podemos utilizar el siguiente prompt para la resolución de estos procesos:

Ahora, vamos a unir el "df" con la base "zoop_pay", leída a partir de la URL "url_zoop_pay", generando un nuevo "df". Para unir las bases, utilizaremos la columna "ID_cliente". Además, ajustaremos la columna "fecha" al formato datetime, donde su formato en la base de datos es "YYYY-MM-DD".

Utilizando la respuesta de ChatGPT, obtenemos el siguiente código:

---
---

In [16]:
import pandas as pd

# Sustituye url_zoop_pay por la URL real proporcionada para la base zoop_pay
zoop_pay = pd.read_csv(url_zoop_pay)

# Uniendo el DataFrame df con la base zoop_pay utilizando la columna "ID_cliente"
df = pd.merge(df, zoop_pay, on="ID_cliente")

# Ajustando la columna "fecha" al formato datetime
df['fecha'] = pd.to_datetime(df['fecha'], format='%Y-%m-%d')

# Mostrando las primeras filas del DataFrame resultante para verificación
df.head()

,ID_compra,fecha,horario,categoria,precio_unitario,cantidad,envio,metodo_pago,ID_cliente,edad,sexo_biologico,ciudad,estado,region,cashback,nota,zoop_pay
0,6,2023-01-03,20:40,Electrónicos,4457.9,4,713.26,Paypal,6149,30,Masculino,Hermosillo,Sonora,Noroeste,Sí,10,No
1,5,2023-01-03,21:48,Herramientas y construcción,115.9,1,0.00,Transferencia,9491,36,Masculino,Ciudad de México,Ciudad de México,Centro,Sí,8,Sí
2,9,2023-01-03,17:08,Belleza e higiene,68.9,2,13.78,Tarjeta de Crédito,5288,39,Femenino,Aguascalientes,Aguascalientes,Centro-Norte,No,7,No
3,4,2023-01-03,14:29,Herramientas y construcción,80.9,5,40.45,Transferencia,9679,35,Masculino,Veracruz,Veracruz,Golfo,Sí,9,Sí
4,8,2023-01-03,18:02,Belleza e higiene,165.0,4,0.00,Transferencia,1380,50,Masculino,Ciudad de México,Ciudad de México,Centro,No,9,No

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6169 entries, 0 to 6168
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_compra        6169 non-null   int64
 1   fecha            6169 non-null   datetime64[ns]
 2   horario          6169 non-null   object
 3   categoria        6169 non-null   object
 4   precio_unitario  6169 non-null   float64
 5   cantidad         6169 non-null   int64
 6   envio            6169 non-null   float64
 7   metodo_pago      6169 non-null   object
 8   ID_cliente       6169 non-null   int64
 9   edad             6169 non-null   int64
 10  sexo_biologico   6169 non-null   object
 11  ciudad           6169 non-null   object
 12  estado           6169 non-null   object
 13  region           6169 non-null   object
 14  cashback         6169 non-null   object
 15  nota             6169 non-null   int64
 16  zoop_pay         6169 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(5), object(9)
memory usage: 819.4+ KB