## **Leyendo paginas en HTML e XML**

### Importando paginas WEB

In [21]:
import pandas as pd

In [22]:
datos_html = pd.read_html('peliculas_wikipedia.html')

In [23]:
type(datos_html)

list

In [24]:
len(datos_html)

3

In [25]:
top_peliculas = datos_html[1]

top_peliculas

,Film,Release year,Director,Production companies,Rank
0,Citizen Kane,1941,Orson Welles,RKO Radio Pictures,1
1,Casablanca,1942,Michael Curtiz,Warner Bros. Pictures,2
2,The Godfather,1972,Francis Ford Coppola,"Paramount Pictures, Alfran Productions",3
3,Gone with the Wind,1939,Victor Fleming,Selznick International Pictures,4
4,Lawrence of Arabia,1962,David Lean,Horizon Pictures,5
...,...,...,...,...,...
95,The Searchers,1956,John Ford,C. V. Whitney Pictures,96
96,Bringing Up Baby,1938,Howard Hawks,RKO Radio Pictures,97
97,Unforgiven,1992,Clint Eastwood,The Malpaso Company,98
98,Guess Who's Coming to Dinner,1967,Stanley Kramer,Columbia Pictures,99
99,Yankee Doodle Dandy,1942,Michael Curtiz,Warner Bros. Pictures,100

## **escribir archivo HTML**

In [26]:
type(top_peliculas)

top_peliculas.to_html('top_peliculas.html', index=False)

In [27]:
pd.read_html('top_peliculas.html')

[                            Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles
 1                     Casablanca          1942        Michael Curtiz
 2                  The Godfather          1972  Francis Ford Coppola
 3             Gone with the Wind          1939        Victor Fleming
 4             Lawrence of Arabia          1962            David Lean
 ..                           ...           ...                   ...
 95                 The Searchers          1956             John Ford
 96              Bringing Up Baby          1938          Howard Hawks
 97                    Unforgiven          1992        Clint Eastwood
 98  Guess Who's Coming to Dinner          1967        Stanley Kramer
 99           Yankee Doodle Dandy          1942        Michael Curtiz

                       Production companies  Rank
 0                       RKO Radio Pictures     1
 1                    Warner Bros. Pictures     2
 2   Paramount Pictures, Alfran Productions     3
 3          Selznick International Pictures     4
 4                         Horizon Pictures     5
 ..                                     ...   ...
 95                  C. V. Whitney Pictures    96
 96                      RKO Radio Pictures    97
 97                     The Malpaso Company    98
 98                       Columbia Pictures    99
 99                   Warner Bros. Pictures   100

 [100 rows x 5 columns]]

In [28]:
top_peliculas.to_csv('top_peliculas_1998.csv', index=False)

In [29]:
datos =pd.read_csv('top_peliculas_1998.csv')
datos

,Film,Release year,Director,Production companies,Rank
0,Citizen Kane,1941,Orson Welles,RKO Radio Pictures,1
1,Casablanca,1942,Michael Curtiz,Warner Bros. Pictures,2
2,The Godfather,1972,Francis Ford Coppola,"Paramount Pictures, Alfran Productions",3
3,Gone with the Wind,1939,Victor Fleming,Selznick International Pictures,4
4,Lawrence of Arabia,1962,David Lean,Horizon Pictures,5
...,...,...,...,...,...
95,The Searchers,1956,John Ford,C. V. Whitney Pictures,96
96,Bringing Up Baby,1938,Howard Hawks,RKO Radio Pictures,97
97,Unforgiven,1992,Clint Eastwood,The Malpaso Company,98
98,Guess Who's Coming to Dinner,1967,Stanley Kramer,Columbia Pictures,99
99,Yankee Doodle Dandy,1942,Michael Curtiz,Warner Bros. Pictures,100

### **Leyendo y Escribiendo archivs XML**

In [30]:
import pandas as pd

In [31]:
datos_imdb =pd.read_xml('imdb_top_1000.xml')

In [32]:
datos_imdb.head(3)

,index,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"

In [34]:
datos_imdb.to_xml('peliculas_imdb.xml', index=False)

In [40]:
pd.read_xml('peliculas_imdb.xml').head(3)

,index,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"

ejercicio

In [41]:
paises_html = pd.read_html('anexo_paises.html')

In [42]:
type(paises_html)

list

In [43]:
len(paises_html)

7

In [45]:
poblacion = paises_html[0]

In [48]:
poblacion.head(3)

,N.º,País (o territorio dependiente),Proyección exponencial de la población al 1/7/2025[7]​,Total mun- dial (%),Cambio medio anual (%)[8]​,Cambio absoluto anual promedio,Cambio medio abs. total anual (%),Años para even- tual du- pli- ca- ción[9]​,"Censo más reciente, última estimación oficial, proyección de la ONU o reloj de población nacional",Fecha de esta última cifra de población en particular (d/mm/aaaa)[10]​,Tipo[11]​,Enlace o hipervínculo (usualmente de tipo oficial) de esta última cifra de población
0,1,India,1 417 492 000,1754,090,12 692 000,1524,78,1 417 492 000,1/07/2025,A,web.archive.org
1,2,China[12]​,1 407 934 000,1742,-005,-1 390 000,-,-,1 408 280 000,31/12/2024,E,www.stats.gov.cn
2,3,Estados Unidos,342 181 000,423,061,2 084 000,250,114,341 820 000,23/05/2025,R,www.census.gov

otra forma de leerla

In [47]:
pd.read_html('https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n')[0]

,N.º,País (o territorio dependiente),Proyección exponencial de la población al 1/7/2025[7]​,Total mun- dial (%),Cambio medio anual (%)[8]​,Cambio absoluto anual promedio,Cambio medio abs. total anual (%),Años para even- tual du- pli- ca- ción[9]​,"Censo más reciente, última estimación oficial, proyección de la ONU o reloj de población nacional",Fecha de esta última cifra de población en particular (d/mm/aaaa)[10]​,Tipo[11]​,Enlace o hipervínculo (usualmente de tipo oficial) de esta última cifra de población
0,1,India,1 417 492 000,1754,090,12 692 000,1524,78,1 417 492 000,1/07/2025,A,web.archive.org
1,2,China[12]​,1 407 934 000,1742,-005,-1 390 000,-,-,1 408 280 000,31/12/2024,E,www.stats.gov.cn
2,3,Estados Unidos,342 181 000,423,061,2 084 000,250,114,341 820 000,23/05/2025,R,www.census.gov
3,4,Indonesia,285 783 000,354,117,3 337 000,401,60,282 477 584,30/06/2024,E,dispendukcapil.acehtimurkab.go.id
4,5,Pakistán,256 204 000,317,256,6 567 000,788,27,241 499 431,1/03/2023,C,www.pbs.gov.pk
...,...,...,...,...,...,...,...,...,...,...,...,...
241,242,Islas Cocos (Australia),600,000,174,0,000,40,593,11/08/2021,C,www.citypopulation.de
242,243,Islas Ultramarinas Menores de los Estados Unidos,100,000,-496,0,000,-,190,1/04/2010,C,www.statoids.com
243,244,Islas Pitcairn (RU),30,000,-111,0,000,-,35,1/07/2023,E,www.immigration.pn
244,NaN,Mundo,8 083 295 000,10000,103,83 285 000,10000,68,8 202 273 000,23/05/2025,R,www.worldometers.info
245,N°,País (o territorio dependiente),Proyección exponencial de la población al 1/7/...,Total mun- dial (%),Cambio medio anual (%),Cambio absoluto anual promedio,Cambio medio abs. total anual (%),Años para even- tual du- pli- ca- ción,"Censo más reciente, última estimación oficial,...",Fecha de esta última cifra de población en par...,Tipo,Enlace o hipervínculo (usualmente de tipo ofic...