## **Leyendo archivos Excel**

### importando archivos Excel

In [1]:
import pandas as pd

# Leer la hoja de cálculo de un archivo Excel
datos_co2 = pd.read_excel("emisiones_CO2.xlsx")

In [2]:
datos_co2.head()  # Muestra las primeras filas del DataFrame

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
0,Afganistán,AFG,1750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afganistán,AFG,1751,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afganistán,AFG,1752,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afganistán,AFG,1753,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afganistán,AFG,1754,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### averiguar hojas del excel

In [3]:
pd.ExcelFile("emisiones_CO2.xlsx").sheet_names  
# Muestra los nombres de las hojas en el archivo Excel

['emisiones_C02', 'emisiones_percapita', 'fuentes']

In [4]:
percapita = pd.read_excel("emisiones_CO2.xlsx",sheet_name= 'emisiones_percapita')

In [5]:
percapita.tail()  
# Muestra las ultimos filas del DataFrame

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros
63099,Global,WLD,2017,4749682.0,1908857.0,1610910.0,940144.0,198416.0,51579.0,39776.0
63100,Global,WLD,2018,4792753.0,1919213.0,1596350.0,979965.0,204225.0,53634.0,39366.0
63101,Global,WLD,2019,4775633.0,1896468.0,1589920.0,984878.0,208309.0,56569.0,39490.0
63102,Global,WLD,2020,4497423.0,1807760.0,1427353.0,963695.0,208844.0,51981.0,37789.0
63103,Global,WLD,2021,4693699.0,1893923.0,1496614.0,1001585.0,211472.0,52663.0,37443.0

In [6]:
percapita.sample(5)  
# Muestra 5 filas aleatorias del DataFrame

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros
51413,Islas Salomón,SLB,1755,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59614,Tanzania,TZA,1796,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56157,Timor Oriental,TLS,1875,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44819,Puerto Rico,PRI,1961,0.0,NaN,NaN,NaN,NaN,NaN,NaN
39081,Países Bajos,NLD,1935,4418436.0,4009373.0,387948.0,0.0,21115.0,0.0,NaN

In [7]:
fuentes = pd.read_excel("emisiones_CO2.xlsx",sheet_name= 'fuentes')

In [8]:
fuentes.tail(5)

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
63099,Global,WLD,2017,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63100,Global,WLD,2018,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63101,Global,WLD,2019,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63102,Global,WLD,2020,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63103,Global,WLD,2021,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."

#### selecionar intervalo de columnas

In [9]:
intervalo = pd.read_excel("emisiones_CO2.xlsx", sheet_name= 'emisiones_C02' , usecols= 'A:D')
intervalo

             País ISO 3166-1 alpha-3   Año         Total
0      Afganistán                AFG  1750  0.000000e+00
1      Afganistán                AFG  1751  0.000000e+00
2      Afganistán                AFG  1752  0.000000e+00
3      Afganistán                AFG  1753  0.000000e+00
4      Afganistán                AFG  1754  0.000000e+00
...           ...                ...   ...           ...
63099      Global                WLD  2017  3.609674e+10
63100      Global                WLD  2018  3.682651e+10
63101      Global                WLD  2019  3.708256e+10
63102      Global                WLD  2020  3.526409e+10
63103      Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

#### seleccionar numeros de filas

In [10]:
intervalo_2 = pd.read_excel("emisiones_CO2.xlsx", sheet_name= 'emisiones_C02' , usecols= 'A:D', nrows= 10)
intervalo_2

         País ISO 3166-1 alpha-3   Año  Total
0  Afganistán                AFG  1750      0
1  Afganistán                AFG  1751      0
2  Afganistán                AFG  1752      0
3  Afganistán                AFG  1753      0
4  Afganistán                AFG  1754      0
5  Afganistán                AFG  1755      0
6  Afganistán                AFG  1756      0
7  Afganistán                AFG  1757      0
8  Afganistán                AFG  1758      0
9  Afganistán                AFG  1759      0

#### escribir archivo excel

In [11]:
intervalo.to_excel("emisiones_CO2_intervalo.xlsx", index= False)

#### leer archivo creado

In [12]:
pd.read_excel("emisiones_CO2_intervalo.xlsx")

             País ISO 3166-1 alpha-3   Año         Total
0      Afganistán                AFG  1750  0.000000e+00
1      Afganistán                AFG  1751  0.000000e+00
2      Afganistán                AFG  1752  0.000000e+00
3      Afganistán                AFG  1753  0.000000e+00
4      Afganistán                AFG  1754  0.000000e+00
...           ...                ...   ...           ...
63099      Global                WLD  2017  3.609674e+10
63100      Global                WLD  2018  3.682651e+10
63101      Global                WLD  2019  3.708256e+10
63102      Global                WLD  2020  3.526409e+10
63103      Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

## LEER ARCHIVOS EXCEL EN GOOGLE SHEETS

link : https://docs.google.com/spreadsheets/d/1hV4_35gr1sYN-SfcSzsak0lB0QSb5iWoVOASfsmE4iw/edit?usp=sharing

https://docs.google.com/spreadsheets/d/1hV4_35gr1sYN-SfcSzsak0lB0QSb5iWoVOASfsmE4iw/edit?usp=sharing

In [48]:
sheet_id = '1hV4_35gr1sYN-SfcSzsak0lB0QSb5iWoVOASfsmE4iw'

url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

#url = 'https://docs.google.com/spreadsheets/d/1hV4_35gr1sYN-SfcSzsak0lB0QSb5iWoVOASfsmE4iw/edit?usp=sharing'

print(url)

https://docs.google.com/spreadsheets/d/1hV4_35gr1sYN-SfcSzsak0lB0QSb5iWoVOASfsmE4iw/gviz/tq?tqx=out:csv&sheet

In [50]:
datos_co2_sheets = pd.read_csv(url)

datos_co2_sheets

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
0,Afganistán,AFG,1750,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afganistán,AFG,1751,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afganistán,AFG,1752,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afganistán,AFG,1753,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afganistán,AFG,1754,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,"36,096,739,276","14,506,973,805","12,242,627,935","7,144,928,128","1,507,923,185","391,992,176","302,294,047","4,749,682"
63100,Global,WLD,2018,"36,826,506,600","14,746,830,688","12,266,016,285","7,529,846,784","1,569,218,392","412,115,746","302,478,706","4,792,753"
63101,Global,WLD,2019,"37,082,558,969","14,725,978,025","12,345,653,374","7,647,528,220","1,617,506,786","439,253,991","306,638,573","4,775,633"
63102,Global,WLD,2020,"35,264,085,734","14,174,564,010","11,191,808,551","7,556,290,283","1,637,537,532","407,583,673","296,301,685","4,497,423"
63103,Global,WLD,2021,"37,123,850,352","14,979,598,083","11,837,159,116","7,921,829,472","1,672,592,372","416,525,563","296,145,746","4,693,699"

## **LEER HOJA ESPECIFICA** "emisiones_percapita"

In [53]:
sheet_id = '1hV4_35gr1sYN-SfcSzsak0lB0QSb5iWoVOASfsmE4iw'
sheet_name = 'emisiones_percapita'

url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

print(url_percapita)

https://docs.google.com/spreadsheets/d/1hV4_35gr1sYN-SfcSzsak0lB0QSb5iWoVOASfsmE4iw/gviz/tq?tqx=out:csv&sheet=emisiones_percapita

In [55]:
percapita_sheets = pd.read_csv(url_percapita)

percapita_sheets

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros
0,Afganistán,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afganistán,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afganistán,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afganistán,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afganistán,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,"4,749,682","1,908,857","1,610,910","940,144","198,416","51,579","39,776"
63100,Global,WLD,2018,"4,792,753","1,919,213","1,596,350","979,965","204,225","53,634","39,366"
63101,Global,WLD,2019,"4,775,633","1,896,468","1,589,920","984,878","208,309","56,569","39,490"
63102,Global,WLD,2020,"4,497,423","1,807,760","1,427,353","963,695","208,844","51,981","37,789"
63103,Global,WLD,2021,"4,693,699","1,893,923","1,496,614","1,001,585","211,472","52,663","37,443"

## **LEER HOJA ESPECIFICA** "fuentes"

In [ ]:
sheet_id = '1hV4_35gr1sYN-SfcSzsak0lB0QSb5iWoVOASfsmE4iw'
sheet_name = 'fuentes' # NOMBRE DE LA HOJA

url_fuentes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

print(url_fuentes)

https://docs.google.com/spreadsheets/d/1hV4_35gr1sYN-SfcSzsak0lB0QSb5iWoVOASfsmE4iw/gviz/tq?tqx=out:csv&sheet=fuentes

In [60]:
fuentes_sheets = pd.read_csv(url_fuentes)

fuentes_sheets.head(5)

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
0,Afganistán,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afganistán,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afganistán,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afganistán,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afganistán,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]

Desafío: leyendo datos de otro link

https://docs.google.com/spreadsheets/d/14hPDO3Dmggshh_H7_LUBQMclf8D4OUuAqbpUpOl3qHs/edit?usp=sharing

sheet_id_2 = '14hPDO3Dmggshh_H7_LUBQMclf8D4OUuAqbpUpOl3qHs'

url_carbon = f'https://docs.google.com/spreadsheets/d/{sheet_id_2}/edit?usp=sharing'

In [67]:
sheet_id_2 = '14hPDO3Dmggshh_H7_LUBQMclf8D4OUuAqbpUpOl3qHs'

url_carbon = f'https://docs.google.com/spreadsheets/d/{sheet_id_2}/gviz/tq?tqx=out:csv&sheet='

print(url_carbon)

https://docs.google.com/spreadsheets/d/14hPDO3Dmggshh_H7_LUBQMclf8D4OUuAqbpUpOl3qHs/gviz/tq?tqx=out:csv&sheet=

In [70]:
carbon_sheets = pd.read_csv(url_carbon)

carbon_sheets.head(5)

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),"191,745,115","167,681,579","95,957,742","8,472,111","75,545,827","68,467,956",...,"29,650,624","259,295,334","18,562,366","146,235,617","172,896,741","149,789,334","131,694,556","1,632,953","159,824,372","159,824,372"
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),"553,661,955","544,538,649","543,557,223","70,898,423","836,804,405","912,141,485",...,"985,522,312","950,695,879","1,036,293,852","1,099,779,111","113,504,405","1,031,811,348","81,330,073","777,674,934","792,137,069","792,137,069"
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),"1,819,541,634","124,281,022","683,699,826","638,307,036","645,355,189","605,436,253",...,"166,942,319","150,324,046","1,533,630,039","1,668,337,371","160,377,515","1,557,664,358","1,788,786,074","1,782,738,948","169,224,832","169,224,832"
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),"7,521,831,658","723,537,924","69,630,787","6,724,177,518","6,541,578,914","6,733,479,486",...,"5,850,886,105","5,944,654,173","5,942,800,412","5,807,127,723","6,026,181,822","6,080,600,282","6,104,133,912","6,362,975,399","6,481,217,432","6,481,217,432"