## **Leyendo archivos Excel**

### importando archivos Excel

In [2]:
import pandas as pd

# Leer la hoja de cálculo de un archivo Excel
datos_co2 = pd.read_excel("emisiones_CO2.xlsx")

In [4]:
datos_co2.head()  # Muestra las primeras filas del DataFrame

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
0,Afganistán,AFG,1750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afganistán,AFG,1751,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afganistán,AFG,1752,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afganistán,AFG,1753,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afganistán,AFG,1754,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### averiguar hojas del excel

In [7]:
pd.ExcelFile("emisiones_CO2.xlsx").sheet_names  
# Muestra los nombres de las hojas en el archivo Excel

['emisiones_C02', 'emisiones_percapita', 'fuentes']

In [9]:
percapita = pd.read_excel("emisiones_CO2.xlsx",sheet_name= 'emisiones_percapita')

In [ ]:
percapita.tail()  
# Muestra las ultimos filas del DataFrame

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros
63099,Global,WLD,2017,4749682.0,1908857.0,1610910.0,940144.0,198416.0,51579.0,39776.0
63100,Global,WLD,2018,4792753.0,1919213.0,1596350.0,979965.0,204225.0,53634.0,39366.0
63101,Global,WLD,2019,4775633.0,1896468.0,1589920.0,984878.0,208309.0,56569.0,39490.0
63102,Global,WLD,2020,4497423.0,1807760.0,1427353.0,963695.0,208844.0,51981.0,37789.0
63103,Global,WLD,2021,4693699.0,1893923.0,1496614.0,1001585.0,211472.0,52663.0,37443.0

In [16]:
percapita.sample(5)  
# Muestra 5 filas aleatorias del DataFrame

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros
62211,Zambia,ZMB,1945,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8155,Brunei Darussalam,BRN,2017,21635841.0,0.0,4479134.0,15855795.0,0.0,1300912.0,NaN
42148,Pakistán,PAK,2010,791489.0,89615.0,319587.0,324618.0,57670.0,0.0,NaN
38335,Namibia,NAM,2005,1177862.0,26175.0,1151687.0,0.0,0.0,0.0,NaN
28401,Kenia,KEN,1863,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
fuentes = pd.read_excel("emisiones_CO2.xlsx",sheet_name= 'fuentes')

In [18]:
fuentes.tail(5)

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
63099,Global,WLD,2017,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63100,Global,WLD,2018,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63101,Global,WLD,2019,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63102,Global,WLD,2020,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63103,Global,WLD,2021,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."

#### selecionar intervalo de columnas

In [19]:
intervalo = pd.read_excel("emisiones_CO2.xlsx", sheet_name= 'emisiones_C02' , usecols= 'A:D')
intervalo

             País ISO 3166-1 alpha-3   Año         Total
0      Afganistán                AFG  1750  0.000000e+00
1      Afganistán                AFG  1751  0.000000e+00
2      Afganistán                AFG  1752  0.000000e+00
3      Afganistán                AFG  1753  0.000000e+00
4      Afganistán                AFG  1754  0.000000e+00
...           ...                ...   ...           ...
63099      Global                WLD  2017  3.609674e+10
63100      Global                WLD  2018  3.682651e+10
63101      Global                WLD  2019  3.708256e+10
63102      Global                WLD  2020  3.526409e+10
63103      Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

#### seleccionar numeros de filas

In [20]:
intervalo_2 = pd.read_excel("emisiones_CO2.xlsx", sheet_name= 'emisiones_C02' , usecols= 'A:D', nrows= 10)
intervalo_2

         País ISO 3166-1 alpha-3   Año  Total
0  Afganistán                AFG  1750      0
1  Afganistán                AFG  1751      0
2  Afganistán                AFG  1752      0
3  Afganistán                AFG  1753      0
4  Afganistán                AFG  1754      0
5  Afganistán                AFG  1755      0
6  Afganistán                AFG  1756      0
7  Afganistán                AFG  1757      0
8  Afganistán                AFG  1758      0
9  Afganistán                AFG  1759      0

#### escribir archivo excel

In [21]:
intervalo.to_excel("emisiones_CO2_intervalo.xlsx", index= False)

#### leer archivo creado

In [22]:
pd.read_excel("emisiones_CO2_intervalo.xlsx")

             País ISO 3166-1 alpha-3   Año         Total
0      Afganistán                AFG  1750  0.000000e+00
1      Afganistán                AFG  1751  0.000000e+00
2      Afganistán                AFG  1752  0.000000e+00
3      Afganistán                AFG  1753  0.000000e+00
4      Afganistán                AFG  1754  0.000000e+00
...           ...                ...   ...           ...
63099      Global                WLD  2017  3.609674e+10
63100      Global                WLD  2018  3.682651e+10
63101      Global                WLD  2019  3.708256e+10
63102      Global                WLD  2020  3.526409e+10
63103      Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

## LEER ARCHIVOS EXCEL EN GOOGLE SHEETS