### DESAFIO

En este curso trabajaremos con el conjunto de datos presentes en el archivo datos_hosting.json y, para avanzar en nuestros estudios sobre los datos que proporciona este archivo, entenderemos qué información trae cada columna.

- evaluacion_general: se refiere a la puntuación media otorgada para evaluar el alojamiento en- la propiedad.
- experiencia_local: describe las experiencias ofrecidas durante su estancia en la propiedad.
- max_hospedes: informa el número máximo de invitados que permite la ubicación.
- descripcion_local: describe la propiedad.
- descripcion_vecindad: describe el vecindario alrededor de la propiedad.
- cantidad_baños: informa el número de baños disponibles.
- cantidad_cuartos: informa el número de habitaciones disponibles.
- cantidad_camas: informa el número de camas disponibles.
- modelo_cama: informa el modelo de cama ofrecido.
- comodidades: informa las comodidades que ofrece la propiedad.
- cuota_deposito: informa la tarifa mínima de depósito para la seguridad del hosting.
- cuota_limpieza: informa el cargo cobrado por el servicio de limpieza.
- precio: se refiere al precio base a cobrar por la estancia diaria en la propiedad.

In [70]:
# Import de pandas
import pandas as pd
# Leer el archivo json con read_json
datos_1 = pd.read_json('dados_vendas_clientes.json')
# Aplicar json_normalize en la columna dados_vendas
datos_1 = pd.json_normalize(datos_1['dados_vendas'])
# Mostrar valores
datos_1

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [71]:
# Import de pandas
import pandas as pd
# Leer el archivo json con read_json
datos_2 = pd.read_json('dados_locacao_imoveis.json')
# Aplicar json_normalize en la columna dados_locacao
datos_2 = pd.json_normalize(datos_2['dados_locacao'])
# Mostrar valores
datos_2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

In [72]:
# Colectar los valores de las columnas y verificar
columnas = list(datos_1.columns)
columnas

# Destrincar las listas con explode
datos_1 = datos_1.explode(columnas[1:])
# Resetear los index de las líneas
datos_1.reset_index(drop=True,inplace=True)
# Observar el DataFrame
datos_1

# Verificar los tipos de datos con info
datos_1.info()

# La columna numérica es el 'Valor da compra'
datos_1['Valor da compra']

# Iniciar la transformación
# Import de la biblioteca numpy
import numpy as np
# Remover los textos presentes en la base
# Cambiar las comas separadoras del decimal por punto
datos_1['Valor da compra'] = datos_1['Valor da compra'].apply(lambda x: x.replace('R$ ', '').replace(',','.').strip())
# Cambiar los tipo de datos para float
datos_1['Valor da compra'] = datos_1['Valor da compra'].astype(np.float64)
# Verificar la transformación
datos_1.info()
datos_1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

   Data de venda             Cliente  Valor da compra
0     06/06/2022     @ANA _LUCIA 321           836.50
1     06/06/2022  DieGO ARMANDIU 210           573.33
2     06/06/2022  DieGO ARMANDIU 210           392.80
3     06/06/2022  DieGO ARMANDIU 210           512.34
4     07/06/2022  Isabely JOanes 738           825.31
5     07/06/2022  Isabely JOanes 738           168.07
6     07/06/2022  Isabely JOanes 738           339.18
7     07/06/2022  Isabely JOanes 738           314.69
8     08/06/2022  Isabely JOanes 738           682.05
9     08/06/2022    JOãO Gabriel 671           386.34
10    08/06/2022  Julya meireles 914           622.65
11    08/06/2022  Julya meireles 914           630.79
12    09/06/2022  Julya meireles 914           390.30
13    09/06/2022     MaRIA Julia 444           759.16
14    09/06/2022     MaRIA Julia 444           334.47
15    09/06/2022     MaRIA Julia 444           678.78
16    10/06/2022     MaRIA Julia 444           314.24
17    10/06/2022     PEDRO PASCO 812           311.15
18    10/06/2022    Paulo castro 481           899.16
19    10/06/2022   Thiago fritzz 883           885.24

In [73]:
# Colectar los valores de las columnas y verificar
columnas = list(datos_2.columns)
columnas

# Destrincar las listas con explode
datos_2 = datos_2.explode(columnas[1:])
# Resetear los index de las líneas
datos_2.reset_index(drop=True,inplace=True)
# Observar el DataFrame
datos_2

# Verificar los tipos de datos con info
datos_2.info()

# La columna numérica es el 'valor_aluguel'
datos_2['valor_aluguel']

# Iniciar la transformación
# Import de la biblioteca numpy
import numpy as np
# Remover los textos presentes en la base
# Cambiar las comas separadoras del decimal por punto
datos_2['valor_aluguel'] = datos_2['valor_aluguel'].apply(lambda x: x.replace('$ ', '').replace(' reais', '').replace(',','.').strip())
# Cambiar los tipos de datos para float
datos_2['valor_aluguel'] = datos_2['valor_aluguel'].astype(np.float64)
# Verificar la transformación
datos_2.info()
datos_2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,1000.0
1,A101 (blocoAP),01/07/2022,03/07/2022,2500.0
2,A102 (blocoAP),02/06/2022,02/06/2022,1100.0
3,A102 (blocoAP),02/07/2022,06/07/2022,2600.0
4,B201 (blocoAP),03/06/2022,07/06/2022,1200.0
5,B201 (blocoAP),03/07/2022,03/07/2022,2700.0
6,B202 (blocoAP),04/06/2022,07/06/2022,1300.0
7,B202 (blocoAP),04/07/2022,05/07/2022,2800.0
8,C301 (blocoAP),05/06/2022,10/06/2022,1400.0
9,C301 (blocoAP),05/07/2022,09/07/2022,2900.0
10,C302 (blocoAP),06/06/2022,08/06/2022,1500.0
11,C302 (blocoAP),06/07/2022,12/07/2022,1200.0
12,D401 (blocoAP),07/06/2022,07/06/2022,1600.0
13,D401 (blocoAP),07/07/2022,09/07/2022,1300.0
14,D402 (blocoAP),08/06/2022,10/06/2022,1700.0
15,D402 (blocoAP),08/07/2022,14/07/2022,1400.0
16,E501 (blocoAP),09/06/2022,10/06/2022,1800.0
17,E501 (blocoAP),09/07/2022,09/07/2022,1500.0
18,E502 (blocoAP),10/06/2022,16/06/2022,1900.0
19,E502 (blocoAP),10/07/2022,12/07/2022,1600.0
20,F601 (blocoAP),11/06/2022,17/06/2022,2000.0
21,F601 (blocoAP),11/07/2022,13/07/2022,1000.0
22,F602 (blocoAP),12/06/2022,15/06/2022,2100.0
23,F602 (blocoAP),12/07/2022,12/07/2022,1100.0
24,G701 (blocoAP),13/06/2022,19/06/2022,2200.0
25,G701 (blocoAP),13/07/2022,20/07/2022,1200.0
26,G702 (blocoAP),14/06/2022,15/06/2022,2300.0
27,G702 (blocoAP),14/07/2022,17/07/2022,2100.0
28,H801 (blocoAP),15/06/2022,18/06/2022,2400.0
29,H801 (blocoAP),15/07/2022,16/07/2022,2200.0

In [74]:
# Transformar los textos de Cliente para texto en minúscula
datos_1['Cliente'] = datos_1['Cliente'].str.lower()
# Verificar el resultado
datos_1.head()

  Data de venda             Cliente  Valor da compra
0    06/06/2022     @ana _lucia 321           836.50
1    06/06/2022  diego armandiu 210           573.33
2    06/06/2022  diego armandiu 210           392.80
3    06/06/2022  diego armandiu 210           512.34
4    07/06/2022  isabely joanes 738           825.31

In [75]:
# Opción de substitución - necesario verificar el resultado de la substitución
# Regex no selecciona todas las letras de a-z y espacios en blanco ' '
# Todo que satisface el regex es borrado
datos_1['Cliente'].str.replace('[^a-z ]', '', regex=True)

0          ana lucia
1     diego armandiu
2     diego armandiu
3     diego armandiu
4     isabely joanes
5     isabely joanes
6     isabely joanes
7     isabely joanes
8     isabely joanes
9        joo gabriel
10    julya meireles
11    julya meireles
12    julya meireles
13       maria julia
14       maria julia
15       maria julia
16       maria julia
17       pedro pasco
18      paulo castro
19     thiago fritzz
Name: Cliente, dtype: object

In [76]:
# Realizar la substitución de los datos en la columna textual
datos_1['Cliente'] = datos_1['Cliente'].str.replace('[^a-z ]', '', regex=True).str.strip()
# Visualizar el resultado final
datos_1.head()

  Data de venda         Cliente  Valor da compra
0    06/06/2022       ana lucia           836.50
1    06/06/2022  diego armandiu           573.33
2    06/06/2022  diego armandiu           392.80
3    06/06/2022  diego armandiu           512.34
4    07/06/2022  isabely joanes           825.31

In [77]:
datos_2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,1000.0
1,A101 (blocoAP),01/07/2022,03/07/2022,2500.0
2,A102 (blocoAP),02/06/2022,02/06/2022,1100.0
3,A102 (blocoAP),02/07/2022,06/07/2022,2600.0
4,B201 (blocoAP),03/06/2022,07/06/2022,1200.0
5,B201 (blocoAP),03/07/2022,03/07/2022,2700.0
6,B202 (blocoAP),04/06/2022,07/06/2022,1300.0
7,B202 (blocoAP),04/07/2022,05/07/2022,2800.0
8,C301 (blocoAP),05/06/2022,10/06/2022,1400.0
9,C301 (blocoAP),05/07/2022,09/07/2022,2900.0
10,C302 (blocoAP),06/06/2022,08/06/2022,1500.0
11,C302 (blocoAP),06/07/2022,12/07/2022,1200.0
12,D401 (blocoAP),07/06/2022,07/06/2022,1600.0
13,D401 (blocoAP),07/07/2022,09/07/2022,1300.0
14,D402 (blocoAP),08/06/2022,10/06/2022,1700.0
15,D402 (blocoAP),08/07/2022,14/07/2022,1400.0
16,E501 (blocoAP),09/06/2022,10/06/2022,1800.0
17,E501 (blocoAP),09/07/2022,09/07/2022,1500.0
18,E502 (blocoAP),10/06/2022,16/06/2022,1900.0
19,E502 (blocoAP),10/07/2022,12/07/2022,1600.0
20,F601 (blocoAP),11/06/2022,17/06/2022,2000.0
21,F601 (blocoAP),11/07/2022,13/07/2022,1000.0
22,F602 (blocoAP),12/06/2022,15/06/2022,2100.0
23,F602 (blocoAP),12/07/2022,12/07/2022,1100.0
24,G701 (blocoAP),13/06/2022,19/06/2022,2200.0
25,G701 (blocoAP),13/07/2022,20/07/2022,1200.0
26,G702 (blocoAP),14/06/2022,15/06/2022,2300.0
27,G702 (blocoAP),14/07/2022,17/07/2022,2100.0
28,H801 (blocoAP),15/06/2022,18/06/2022,2400.0
29,H801 (blocoAP),15/07/2022,16/07/2022,2200.0

In [78]:
# Opción de substitución - necesario verificar el resultado de la substitución
# Fue necesario adicionar la barra '\' para ser considerados los paréntesis como caracteres literales
datos_2['apartamento'].str.replace(' \(blocoAP\)', ' ')

<>:3: SyntaxWarning: invalid escape sequence '\('
<>:3: SyntaxWarning: invalid escape sequence '\('
C:\Users\yuri1\AppData\Local\Temp\ipykernel_14340\3219472051.py:3: SyntaxWarning: invalid escape sequence '\('
  datos_2['apartamento'].str.replace(' \(blocoAP\)', ' ')

0     A101 (blocoAP)
1     A101 (blocoAP)
2     A102 (blocoAP)
3     A102 (blocoAP)
4     B201 (blocoAP)
5     B201 (blocoAP)
6     B202 (blocoAP)
7     B202 (blocoAP)
8     C301 (blocoAP)
9     C301 (blocoAP)
10    C302 (blocoAP)
11    C302 (blocoAP)
12    D401 (blocoAP)
13    D401 (blocoAP)
14    D402 (blocoAP)
15    D402 (blocoAP)
16    E501 (blocoAP)
17    E501 (blocoAP)
18    E502 (blocoAP)
19    E502 (blocoAP)
20    F601 (blocoAP)
21    F601 (blocoAP)
22    F602 (blocoAP)
23    F602 (blocoAP)
24    G701 (blocoAP)
25    G701 (blocoAP)
26    G702 (blocoAP)
27    G702 (blocoAP)
28    H801 (blocoAP)
29    H801 (blocoAP)
Name: apartamento, dtype: object

In [79]:
# Realizar la substitución de los datos en la columna textual
datos_2['apartamento'] = datos_2['apartamento'].str.replace(' \(blocoAP\)', '')
# Visualizar el resultado final
datos_2

<>:2: SyntaxWarning: invalid escape sequence '\('
<>:2: SyntaxWarning: invalid escape sequence '\('
C:\Users\yuri1\AppData\Local\Temp\ipykernel_14340\3065583322.py:2: SyntaxWarning: invalid escape sequence '\('
  datos_2['apartamento'] = datos_2['apartamento'].str.replace(' \(blocoAP\)', '')

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,1000.0
1,A101 (blocoAP),01/07/2022,03/07/2022,2500.0
2,A102 (blocoAP),02/06/2022,02/06/2022,1100.0
3,A102 (blocoAP),02/07/2022,06/07/2022,2600.0
4,B201 (blocoAP),03/06/2022,07/06/2022,1200.0
5,B201 (blocoAP),03/07/2022,03/07/2022,2700.0
6,B202 (blocoAP),04/06/2022,07/06/2022,1300.0
7,B202 (blocoAP),04/07/2022,05/07/2022,2800.0
8,C301 (blocoAP),05/06/2022,10/06/2022,1400.0
9,C301 (blocoAP),05/07/2022,09/07/2022,2900.0
10,C302 (blocoAP),06/06/2022,08/06/2022,1500.0
11,C302 (blocoAP),06/07/2022,12/07/2022,1200.0
12,D401 (blocoAP),07/06/2022,07/06/2022,1600.0
13,D401 (blocoAP),07/07/2022,09/07/2022,1300.0
14,D402 (blocoAP),08/06/2022,10/06/2022,1700.0
15,D402 (blocoAP),08/07/2022,14/07/2022,1400.0
16,E501 (blocoAP),09/06/2022,10/06/2022,1800.0
17,E501 (blocoAP),09/07/2022,09/07/2022,1500.0
18,E502 (blocoAP),10/06/2022,16/06/2022,1900.0
19,E502 (blocoAP),10/07/2022,12/07/2022,1600.0
20,F601 (blocoAP),11/06/2022,17/06/2022,2000.0
21,F601 (blocoAP),11/07/2022,13/07/2022,1000.0
22,F602 (blocoAP),12/06/2022,15/06/2022,2100.0
23,F602 (blocoAP),12/07/2022,12/07/2022,1100.0
24,G701 (blocoAP),13/06/2022,19/06/2022,2200.0
25,G701 (blocoAP),13/07/2022,20/07/2022,1200.0
26,G702 (blocoAP),14/06/2022,15/06/2022,2300.0
27,G702 (blocoAP),14/07/2022,17/07/2022,2100.0
28,H801 (blocoAP),15/06/2022,18/06/2022,2400.0
29,H801 (blocoAP),15/07/2022,16/07/2022,2200.0

In [80]:
# Transformar para el tipo datetime definiendo el formato de fecha como DD/MM/AAAA ('%d/%m/%Y')
datos_1['Data de venda'] = pd.to_datetime(datos_1['Data de venda'], format='%d/%m/%Y')
# Visualizar el resultado
datos_1

   Data de venda         Cliente  Valor da compra
0     2022-06-06       ana lucia           836.50
1     2022-06-06  diego armandiu           573.33
2     2022-06-06  diego armandiu           392.80
3     2022-06-06  diego armandiu           512.34
4     2022-06-07  isabely joanes           825.31
5     2022-06-07  isabely joanes           168.07
6     2022-06-07  isabely joanes           339.18
7     2022-06-07  isabely joanes           314.69
8     2022-06-08  isabely joanes           682.05
9     2022-06-08     joo gabriel           386.34
10    2022-06-08  julya meireles           622.65
11    2022-06-08  julya meireles           630.79
12    2022-06-09  julya meireles           390.30
13    2022-06-09     maria julia           759.16
14    2022-06-09     maria julia           334.47
15    2022-06-09     maria julia           678.78
16    2022-06-10     maria julia           314.24
17    2022-06-10     pedro pasco           311.15
18    2022-06-10    paulo castro           899.16
19    2022-06-10   thiago fritzz           885.24

In [81]:
# Verificar el resultado de la transformación
datos_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 612.0+ bytes

In [82]:
# Calcular el total recaudado en compras por cada cliente
total_compras = datos_1.groupby(['Cliente'])['Valor da compra'].sum()
# Visualizar el resultado
total_compras

Cliente
ana lucia          836.50
diego armandiu    1478.47
isabely joanes    2329.30
joo gabriel        386.34
julya meireles    1643.74
maria julia       2086.65
paulo castro       899.16
pedro pasco        311.15
thiago fritzz      885.24
Name: Valor da compra, dtype: float64

In [83]:
# Transformar para el tipo datetime definiendo el formato de fecha como DD/MM/AAAA ('%d/%m/%Y')
datos_2['datas_combinadas_pagamento'] = pd.to_datetime(datos_2['datas_combinadas_pagamento'], format='%d/%m/%Y')
datos_2['datas_de_pagamento'] = pd.to_datetime(datos_2['datas_de_pagamento'], format='%d/%m/%Y')

In [84]:
# Visualizar el resultado
datos_2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),2022-06-01,2022-06-05,1000.0
1,A101 (blocoAP),2022-07-01,2022-07-03,2500.0
2,A102 (blocoAP),2022-06-02,2022-06-02,1100.0
3,A102 (blocoAP),2022-07-02,2022-07-06,2600.0
4,B201 (blocoAP),2022-06-03,2022-06-07,1200.0
5,B201 (blocoAP),2022-07-03,2022-07-03,2700.0
6,B202 (blocoAP),2022-06-04,2022-06-07,1300.0
7,B202 (blocoAP),2022-07-04,2022-07-05,2800.0
8,C301 (blocoAP),2022-06-05,2022-06-10,1400.0
9,C301 (blocoAP),2022-07-05,2022-07-09,2900.0
10,C302 (blocoAP),2022-06-06,2022-06-08,1500.0
11,C302 (blocoAP),2022-07-06,2022-07-12,1200.0
12,D401 (blocoAP),2022-06-07,2022-06-07,1600.0
13,D401 (blocoAP),2022-07-07,2022-07-09,1300.0
14,D402 (blocoAP),2022-06-08,2022-06-10,1700.0
15,D402 (blocoAP),2022-07-08,2022-07-14,1400.0
16,E501 (blocoAP),2022-06-09,2022-06-10,1800.0
17,E501 (blocoAP),2022-07-09,2022-07-09,1500.0
18,E502 (blocoAP),2022-06-10,2022-06-16,1900.0
19,E502 (blocoAP),2022-07-10,2022-07-12,1600.0
20,F601 (blocoAP),2022-06-11,2022-06-17,2000.0
21,F601 (blocoAP),2022-07-11,2022-07-13,1000.0
22,F602 (blocoAP),2022-06-12,2022-06-15,2100.0
23,F602 (blocoAP),2022-07-12,2022-07-12,1100.0
24,G701 (blocoAP),2022-06-13,2022-06-19,2200.0
25,G701 (blocoAP),2022-07-13,2022-07-20,1200.0
26,G702 (blocoAP),2022-06-14,2022-06-15,2300.0
27,G702 (blocoAP),2022-07-14,2022-07-17,2100.0
28,H801 (blocoAP),2022-06-15,2022-06-18,2400.0
29,H801 (blocoAP),2022-07-15,2022-07-16,2200.0

In [85]:
# Para contribuir en la solución del contexto es posible calcular la diferencia de días
# entre la fecha combinada y la fecha de pagamento con dt.days
datos_2['atraso'] = (datos_2['datas_de_pagamento'] - datos_2['datas_combinadas_pagamento']).dt.days

In [86]:
# Observar el nuevo DataFrame
datos_2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atraso
0,A101 (blocoAP),2022-06-01,2022-06-05,1000.0,4
1,A101 (blocoAP),2022-07-01,2022-07-03,2500.0,2
2,A102 (blocoAP),2022-06-02,2022-06-02,1100.0,0
3,A102 (blocoAP),2022-07-02,2022-07-06,2600.0,4
4,B201 (blocoAP),2022-06-03,2022-06-07,1200.0,4
5,B201 (blocoAP),2022-07-03,2022-07-03,2700.0,0
6,B202 (blocoAP),2022-06-04,2022-06-07,1300.0,3
7,B202 (blocoAP),2022-07-04,2022-07-05,2800.0,1
8,C301 (blocoAP),2022-06-05,2022-06-10,1400.0,5
9,C301 (blocoAP),2022-07-05,2022-07-09,2900.0,4
10,C302 (blocoAP),2022-06-06,2022-06-08,1500.0,2
11,C302 (blocoAP),2022-07-06,2022-07-12,1200.0,6
12,D401 (blocoAP),2022-06-07,2022-06-07,1600.0,0
13,D401 (blocoAP),2022-07-07,2022-07-09,1300.0,2
14,D402 (blocoAP),2022-06-08,2022-06-10,1700.0,2
15,D402 (blocoAP),2022-07-08,2022-07-14,1400.0,6
16,E501 (blocoAP),2022-06-09,2022-06-10,1800.0,1
17,E501 (blocoAP),2022-07-09,2022-07-09,1500.0,0
18,E502 (blocoAP),2022-06-10,2022-06-16,1900.0,6
19,E502 (blocoAP),2022-07-10,2022-07-12,1600.0,2
20,F601 (blocoAP),2022-06-11,2022-06-17,2000.0,6
21,F601 (blocoAP),2022-07-11,2022-07-13,1000.0,2
22,F602 (blocoAP),2022-06-12,2022-06-15,2100.0,3
23,F602 (blocoAP),2022-07-12,2022-07-12,1100.0,0
24,G701 (blocoAP),2022-06-13,2022-06-19,2200.0,6
25,G701 (blocoAP),2022-07-13,2022-07-20,1200.0,7
26,G702 (blocoAP),2022-06-14,2022-06-15,2300.0,1
27,G702 (blocoAP),2022-07-14,2022-07-17,2100.0,3
28,H801 (blocoAP),2022-06-15,2022-06-18,2400.0,3
29,H801 (blocoAP),2022-07-15,2022-07-16,2200.0,1

In [87]:
# Calcular el promedio de tiempo de atraso por apartamentos
media_atraso = datos_2.groupby(['apartamento'])['atraso'].mean()

In [88]:
# Visualizar el resultado
media_atraso

apartamento
A101 (blocoAP)    3.0
A102 (blocoAP)    2.0
B201 (blocoAP)    2.0
B202 (blocoAP)    2.0
C301 (blocoAP)    4.5
C302 (blocoAP)    4.0
D401 (blocoAP)    1.0
D402 (blocoAP)    4.0
E501 (blocoAP)    0.5
E502 (blocoAP)    4.0
F601 (blocoAP)    4.0
F602 (blocoAP)    1.5
G701 (blocoAP)    6.5
G702 (blocoAP)    2.0
H801 (blocoAP)    2.0
Name: atraso, dtype: float64