# Projeto desafio 2 - administração de condomínios

## Etapa 1

In [12]:
# Import do pandas
import pandas as pd
# Ler o arquivo json com read_json
dados = pd.read_json('dados_locacao_imoveis.json')
# Aplicar json_normalize na coluna dados_locacao
dados = pd.json_normalize(dados['dados_locacao'])
dados

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

## Etapa 2

In [13]:
# Coletar os valores das colunas e verificar
colunas = list(dados.columns)
colunas

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [14]:
# Destrinchar as listas com explode
dados = dados.explode(colunas[1:])
# Resetar os index das linhas
dados.reset_index(drop=True,inplace=True)
# Observar o DataFrame
dados.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"

In [15]:
# Verificar os tipos de dados com info
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [16]:
# A coluna numérica é a 'valor_aluguel'
dados['valor_aluguel']

0     $ 1000,0 reais
1     $ 2500,0 reais
2     $ 1100,0 reais
3     $ 2600,0 reais
4     $ 1200,0 reais
5     $ 2700,0 reais
6     $ 1300,0 reais
7     $ 2800,0 reais
8     $ 1400,0 reais
9     $ 2900,0 reais
10    $ 1500,0 reais
11    $ 1200,0 reais
12    $ 1600,0 reais
13    $ 1300,0 reais
14    $ 1700,0 reais
15    $ 1400,0 reais
16    $ 1800,0 reais
17    $ 1500,0 reais
18    $ 1900,0 reais
19    $ 1600,0 reais
20    $ 2000,0 reais
21    $ 1000,0 reais
22    $ 2100,0 reais
23    $ 1100,0 reais
24    $ 2200,0 reais
25    $ 1200,0 reais
26    $ 2300,0 reais
27    $ 2100,0 reais
28    $ 2400,0 reais
29    $ 2200,0 reais
Name: valor_aluguel, dtype: object

In [17]:
# Iniciar a transformação
# Import da biblioteca numpy
import numpy as np
# Remover os textos presentes na base
# Trocar as vírgulas separadoras do decimal por ponto
dados['valor_aluguel'] = dados['valor_aluguel'].apply(lambda x: x.replace('$ ', '').replace(' reais', '').replace(',','.').strip())
# Alterar os tipo de dado para float
dados['valor_aluguel'] = dados['valor_aluguel'].astype(np.float64)
# Verificar a transformação
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

## Etapa 3

In [18]:
# Opção de substituição - necessário verificar o resultado da substituição
# Foi necessário adicionar a barra '\' para ser considerados os parênteses como caracteres literais
dados['apartamento'].str.replace(' \(blocoAP\)', '')

<>:3: SyntaxWarning: invalid escape sequence '\('
<>:3: SyntaxWarning: invalid escape sequence '\('
C:\Users\yuri1\AppData\Local\Temp\ipykernel_1536\1800633786.py:3: SyntaxWarning: invalid escape sequence '\('
  dados['apartamento'].str.replace(' \(blocoAP\)', '')

0     A101 (blocoAP)
1     A101 (blocoAP)
2     A102 (blocoAP)
3     A102 (blocoAP)
4     B201 (blocoAP)
5     B201 (blocoAP)
6     B202 (blocoAP)
7     B202 (blocoAP)
8     C301 (blocoAP)
9     C301 (blocoAP)
10    C302 (blocoAP)
11    C302 (blocoAP)
12    D401 (blocoAP)
13    D401 (blocoAP)
14    D402 (blocoAP)
15    D402 (blocoAP)
16    E501 (blocoAP)
17    E501 (blocoAP)
18    E502 (blocoAP)
19    E502 (blocoAP)
20    F601 (blocoAP)
21    F601 (blocoAP)
22    F602 (blocoAP)
23    F602 (blocoAP)
24    G701 (blocoAP)
25    G701 (blocoAP)
26    G702 (blocoAP)
27    G702 (blocoAP)
28    H801 (blocoAP)
29    H801 (blocoAP)
Name: apartamento, dtype: object

In [19]:
# Realizar a substituição dos dados na coluna textual
dados['apartamento'] = dados['apartamento'].str.replace(' \(blocoAP\)', '')
# Visualizar o resultado final
dados

<>:2: SyntaxWarning: invalid escape sequence '\('
<>:2: SyntaxWarning: invalid escape sequence '\('
C:\Users\yuri1\AppData\Local\Temp\ipykernel_1536\3921502988.py:2: SyntaxWarning: invalid escape sequence '\('
  dados['apartamento'] = dados['apartamento'].str.replace(' \(blocoAP\)', '')

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,1000.0
1,A101 (blocoAP),01/07/2022,03/07/2022,2500.0
2,A102 (blocoAP),02/06/2022,02/06/2022,1100.0
3,A102 (blocoAP),02/07/2022,06/07/2022,2600.0
4,B201 (blocoAP),03/06/2022,07/06/2022,1200.0
5,B201 (blocoAP),03/07/2022,03/07/2022,2700.0
6,B202 (blocoAP),04/06/2022,07/06/2022,1300.0
7,B202 (blocoAP),04/07/2022,05/07/2022,2800.0
8,C301 (blocoAP),05/06/2022,10/06/2022,1400.0
9,C301 (blocoAP),05/07/2022,09/07/2022,2900.0
10,C302 (blocoAP),06/06/2022,08/06/2022,1500.0
11,C302 (blocoAP),06/07/2022,12/07/2022,1200.0
12,D401 (blocoAP),07/06/2022,07/06/2022,1600.0
13,D401 (blocoAP),07/07/2022,09/07/2022,1300.0
14,D402 (blocoAP),08/06/2022,10/06/2022,1700.0
15,D402 (blocoAP),08/07/2022,14/07/2022,1400.0
16,E501 (blocoAP),09/06/2022,10/06/2022,1800.0
17,E501 (blocoAP),09/07/2022,09/07/2022,1500.0
18,E502 (blocoAP),10/06/2022,16/06/2022,1900.0
19,E502 (blocoAP),10/07/2022,12/07/2022,1600.0
20,F601 (blocoAP),11/06/2022,17/06/2022,2000.0
21,F601 (blocoAP),11/07/2022,13/07/2022,1000.0
22,F602 (blocoAP),12/06/2022,15/06/2022,2100.0
23,F602 (blocoAP),12/07/2022,12/07/2022,1100.0
24,G701 (blocoAP),13/06/2022,19/06/2022,2200.0
25,G701 (blocoAP),13/07/2022,20/07/2022,1200.0
26,G702 (blocoAP),14/06/2022,15/06/2022,2300.0
27,G702 (blocoAP),14/07/2022,17/07/2022,2100.0
28,H801 (blocoAP),15/06/2022,18/06/2022,2400.0
29,H801 (blocoAP),15/07/2022,16/07/2022,2200.0

## Etapa 4

In [20]:
# Transformar para o tipo datetime definindo o formato de data como DD/MM/AAAA ('%d/%m/%Y')
dados['datas_combinadas_pagamento'] = pd.to_datetime(dados['datas_combinadas_pagamento'], format='%d/%m/%Y')
dados['datas_de_pagamento'] = pd.to_datetime(dados['datas_de_pagamento'], format='%d/%m/%Y')
# Visualizar o resultado
dados

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),2022-06-01,2022-06-05,1000.0
1,A101 (blocoAP),2022-07-01,2022-07-03,2500.0
2,A102 (blocoAP),2022-06-02,2022-06-02,1100.0
3,A102 (blocoAP),2022-07-02,2022-07-06,2600.0
4,B201 (blocoAP),2022-06-03,2022-06-07,1200.0
5,B201 (blocoAP),2022-07-03,2022-07-03,2700.0
6,B202 (blocoAP),2022-06-04,2022-06-07,1300.0
7,B202 (blocoAP),2022-07-04,2022-07-05,2800.0
8,C301 (blocoAP),2022-06-05,2022-06-10,1400.0
9,C301 (blocoAP),2022-07-05,2022-07-09,2900.0
10,C302 (blocoAP),2022-06-06,2022-06-08,1500.0
11,C302 (blocoAP),2022-07-06,2022-07-12,1200.0
12,D401 (blocoAP),2022-06-07,2022-06-07,1600.0
13,D401 (blocoAP),2022-07-07,2022-07-09,1300.0
14,D402 (blocoAP),2022-06-08,2022-06-10,1700.0
15,D402 (blocoAP),2022-07-08,2022-07-14,1400.0
16,E501 (blocoAP),2022-06-09,2022-06-10,1800.0
17,E501 (blocoAP),2022-07-09,2022-07-09,1500.0
18,E502 (blocoAP),2022-06-10,2022-06-16,1900.0
19,E502 (blocoAP),2022-07-10,2022-07-12,1600.0
20,F601 (blocoAP),2022-06-11,2022-06-17,2000.0
21,F601 (blocoAP),2022-07-11,2022-07-13,1000.0
22,F602 (blocoAP),2022-06-12,2022-06-15,2100.0
23,F602 (blocoAP),2022-07-12,2022-07-12,1100.0
24,G701 (blocoAP),2022-06-13,2022-06-19,2200.0
25,G701 (blocoAP),2022-07-13,2022-07-20,1200.0
26,G702 (blocoAP),2022-06-14,2022-06-15,2300.0
27,G702 (blocoAP),2022-07-14,2022-07-17,2100.0
28,H801 (blocoAP),2022-06-15,2022-06-18,2400.0
29,H801 (blocoAP),2022-07-15,2022-07-16,2200.0

In [21]:
# Para contribuir na solução do contexto é possível calcula a diferença de dias
# entre a data combinada e a data de pagamento com dt.days
dados['atraso'] = (dados['datas_de_pagamento'] - dados['datas_combinadas_pagamento']).dt.days
# Observar o novo DataFrame
dados.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atraso
0,A101 (blocoAP),2022-06-01,2022-06-05,1000.0,4
1,A101 (blocoAP),2022-07-01,2022-07-03,2500.0,2
2,A102 (blocoAP),2022-06-02,2022-06-02,1100.0,0
3,A102 (blocoAP),2022-07-02,2022-07-06,2600.0,4
4,B201 (blocoAP),2022-06-03,2022-06-07,1200.0,4

In [22]:
# Calcular a média de tempo de atraso por apartamentos
media_atraso = dados.groupby(['apartamento'])['atraso'].mean()
# Visualizar o resultado
media_atraso

apartamento
A101 (blocoAP)    3.0
A102 (blocoAP)    2.0
B201 (blocoAP)    2.0
B202 (blocoAP)    2.0
C301 (blocoAP)    4.5
C302 (blocoAP)    4.0
D401 (blocoAP)    1.0
D402 (blocoAP)    4.0
E501 (blocoAP)    0.5
E502 (blocoAP)    4.0
F601 (blocoAP)    4.0
F602 (blocoAP)    1.5
G701 (blocoAP)    6.5
G702 (blocoAP)    2.0
H801 (blocoAP)    2.0
Name: atraso, dtype: float64